---
  - name: Setup nginx repo
    sudo: yes
    template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo


  - name: Install nginx
    sudo: yes
    yum: name=nginx state=present


  - name: restart nginx
    sudo: yes
    service: name=nginx state=restarted enabled=yes
    tags:
      - nginx
